dispatcher_count = 10
devices_per_dispatcher = 10
reading_interval_secs = 5
status_interval_secs = 30
upload_interval_secs = 60
base_http_port = 9100
ersha_dispatch_bin = "/usr/local/bin/ersha-dispatch"
prime_rpc_addr = "ersha-prime:9000"

[tls]
cert = "/etc/ersha/keys/client.crt"
key = "/etc/ersha/keys/client.key"
root_ca = "/etc/ersha/keys/root_ca.crt"
domain = "ersha-prime"
