apiVersion: 1

datasources:
  - name: ClickHouse
    uid: ersha-clickhouse
    type: grafana-clickhouse-datasource
    access: proxy
    isDefault: true
    jsonData:
      host: clickhouse
      port: 8123
      protocol: http
      defaultDatabase: ersha_test
